### ISSUE TITLE
supporting flags in clang-cl

### ISSUE THREAD

**Issue by ahebadi78** [microsoft/llvm#149]
My project needs "-fno-access-control" flag to compile unit tests but unfortunately the clang-cl which is the windows compatible clang compiler for visual studio is not supporting this useful flag.
Will the next releases solve this issue or it's because of windows compatibility and will not change? 
Thanks for any comments

**Comment by JosephTremoulet** [comment]
I think the best way to get an answer to that question will be to send it in an email to [the cfe-dev mailing list](https://lists.llvm.org/mailman/listinfo/cfe-dev).

**Comment by zmodem** [comment]
In case someone else runs into this, I've replied here: http://lists.llvm.org/pipermail/cfe-dev/2020-January/064218.html

**Comment by ahebadi78** [comment]
Thanks **Hans Wennborg** from clang-developers answering my question.
The way that a clang-based flag should be used in Microsoft visual studio environment (which basically MSVC doesn't support the special flag I needed) is documented in the URL below but unfortunately it's a little hard to find it.
https://clang.llvm.org/docs/UsersManual.html#the-clang-option
