### ISSUE TITLE
Finish implementation of inline stack probes for x64 CoreCLR (non-prolog case)

### ISSUE THREAD

**Issue by AndyAyersMS** [Microsoft/llvm#22]
The inline stack probe needed for the CoreCLR environment on windows is incomplete, and doesn't actually probe the stack. Implement the necessary code.

**Comment by AndyAyersMS** [comment]
This is done, with #29 getting it mostly right and #32 fixing one remaining issue.

**Comment by roterdam** [comment]
What exactly is an inline stack probe and why is it needed?

**Comment by AndyAyersMS** [comment]
On Windows, applications must carefully grow the stack. See [this writeup](https://support.microsoft.com/en-us/kb/100775) for more details.

For the most part stack growth occurs gradually in small chunks as the call stack deepens, and so no extra code is required. However for large stack frames and/or large allocas, the compiler must ensure that the newly required pages of the stack are probed in the right order before they're used. __chkstk is a helper routine in the CRT that can do this probing.

Jitted code can't take advantage of __chkstk and so we are implementing similar logic here as inline code sequences.
